
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Newtask from '../components/Newtask'
import AllTasks from '../components/AllTasks'


const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Newtask />
      <AllTasks />
    </div>
  )
}

export default Home;